---
checks:
  black:
    ignore_patterns_re:
      - ^c2cgeoportal/commons/c2cgeoportal_commons/alembic/script\.py\.mako$
      - .*\.rst$
      - ^c2cgeoportal/geoportal/c2cgeoportal_geoportal/scaffolds/.*/.*

publish:
  docker:
    images:
      - name: camptocamp/geomapfish
      - name: camptocamp/geomapfish-tools
        group: full
      - name: camptocamp/geomapfish-config
        group: full
      - name: camptocamp/geomapfish-geoportal
      - name: camptocamp/geomapfish-qgisserver
        group: qgis-3.10
        tags:
          - gmf{version}-qgis3.10
      - name: camptocamp/geomapfish-qgisserver
        group: qgis-3.16
        tags:
          - gmf{version}-qgis3.16
      - name: camptocamp/geomapfish-qgisserver
        group: qgis-master
        tags:
          - gmf{version}-qgismaster
